# Generated by Django 5.1.2 on 2024-10-13 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Most Important", "Most Important"),
                            ("Critical", "Critical"),
                            ("Other", "Other"),
                        ],
                        default="Most Important",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Long-Short term", "Long-Short term"),
                        ],
                        default="Long-Short term",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
